https://jakevdp.github.io/PythonDataScienceHandbook/02.04-computation-on-arrays-aggregates.html 

In [1]:
import numpy as np

In [2]:
L = np.random.random(100)
sum(L)

53.14028665470759

In [3]:
np.sum(L)

53.14028665470759

In [4]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

146 ms ± 6.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.28 ms ± 62.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Minimum and Maximum 

In [6]:
min(big_array), max(big_array)

(7.665812464807686e-07, 0.9999983429925897)

In [7]:
np.min(big_array), np.max(big_array)

(7.665812464807686e-07, 0.9999983429925897)

In [8]:
%timeit min(big_array)
%timeit np.min(big_array)

96 ms ± 2.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
512 µs ± 8.55 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
#NumPy aggregates, a shorter syntax
print(big_array.min(), big_array.max(), big_array.sum())

7.665812464807686e-07 0.9999983429925897 500009.74720226123


## Multi dimensional aggregates

In [12]:
M = np.random.random((3, 4))
print(M)

[[0.09390511 0.34444423 0.68864374 0.69283808]
 [0.61769131 0.13493588 0.32313169 0.60805095]
 [0.72551188 0.31278524 0.08802845 0.63408108]]


In [13]:
M.sum()

5.264047642169135

In [14]:
M.min(axis=0) #X

array([0.09390511, 0.13493588, 0.08802845, 0.60805095])

In [15]:
M.max(axis=1) #Y

array([0.69283808, 0.61769131, 0.72551188])

## Other aggregation functions 

NaN-safe counterpart that computes the result while ignoring missing values 

In [16]:
np.sum	np.nansum	Compute sum of elements
np.prod	np.nanprod	Compute product of elements
np.mean	np.nanmean	Compute mean of elements
np.std	np.nanstd	Compute standard deviation
np.var	np.nanvar	Compute variance
np.min	np.nanmin	Find minimum value
np.max	np.nanmax	Find maximum value
np.argmin	np.nanargmin	Find index of minimum value
np.argmax	np.nanargmax	Find index of maximum value
np.median	np.nanmedian	Compute median of elements
np.percentile	np.nanpercentile	Compute rank-based statistics of elements
np.any	N/A	Evaluate whether any elements are true
np.all	N/A	Evaluate whether all elements are true

SyntaxError: invalid syntax (<ipython-input-16-3584f3b70045>, line 1)

In [24]:
!head -9 data/president_heights.csv

order,name,height(cm)
1,George Washington,189
2,John Adams,170
3,Thomas Jefferson,189
4,James Madison,163
5,James Monroe,183
6,John Quincy Adams,171
7,Andrew Jackson,185
8,Martin Van Buren,168


In [25]:
import pandas as pd
data = pd.read_csv('data/president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [26]:
print("Mean height:       ", heights.mean())
print("Standard deviation:", heights.std())
print("Minimum height:    ", heights.min())
print("Maximum height:    ", heights.max())

Mean height:        179.73809523809524
Standard deviation: 6.931843442745892
Minimum height:     163
Maximum height:     193


In [27]:
print("25th percentile:   ", np.percentile(heights, 25))
print("Median:            ", np.median(heights))
print("75th percentile:   ", np.percentile(heights, 75))

25th percentile:    174.25
Median:             182.0
75th percentile:    183.0


In [28]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set()  # set plot style

In [29]:
plt.hist(heights)
plt.title('Height Distribution of US Presidents')
plt.xlabel('height (cm)')
plt.ylabel('number');